---
- name: user and group management
  hosts: webservers
  become: yes

  tasks:
    - name: create devolopers group
      group:
        name: devolopers
        state: present

    - name: create join users
      user:
        name: john
        group: devolopers
        shell: /bin/bash
        state: present
